### ISSUE TITLE
Cookbook ideas for url crate

### ISSUE THREAD

**Issue by brson** [brson/rust-cookbook#40]
These examples are desired to represent the [url](https://docs.rs/url) crate.

- [x] [Parse a URL from a string to a `Url` type](https://github.com/brson/rust-cookbook/issues/33)
- [x] [Create a base URL by removing path segments](https://github.com/brson/rust-cookbook/issues/34)
- [x] [Create new URLs from a base URL](https://github.com/brson/rust-cookbook/issues/35)
- [x] [Extract the URL origin (scheme / host / port)](https://github.com/brson/rust-cookbook/issues/36)
- [x] [Remove fragment identifiers and query pairs from a URL](https://github.com/brson/rust-cookbook/issues/37)
- [x] [Encode binary data as application/x-www-form-urlencoded](https://github.com/brson/rust-cookbook/issues/85)
- [x] [Percent-encode binary data](https://github.com/brson/rust-cookbook/issues/86)

Other ideas very much welcome. Suggest here or just submit a PR.

**Comment by brson** [comment]
Still soliciting good ideas that show off how url is used in practice.

**Comment by budziq** [comment]
I guess examples about parsing and serialization for web with use of url crate might be useful:
- [ ] application/x-www-form-urlencoded [`url::form_urlencoded`](https://docs.rs/url/1.4.0/url/form_urlencoded/index.html) 
- [ ] percent encoding [`url::percent_encoding`](https://docs.rs/url/1.4.0/url/percent_encoding/index.html)

These do not have examples in docs at all

**Comment by dtolnay** [comment]
Thanks! I added those to the top checklist.

**Comment by budziq** [comment]
I guess that all examples are implemented from this section
