### ISSUE TITLE
Cookbook ideas for log crate

### ISSUE THREAD

**Issue by brson** [brson/rust-cookbook#61]
Write examples for these use cases following the existing precedent and guidelines in CONTRIBUTING.md

- [x] [Log a debug message to the console](https://github.com/brson/rust-cookbook/issues/95)
- [x] [Log an error message to the console](https://github.com/brson/rust-cookbook/issues/96)
- [x] Log messages with a custom logger (added in #74)
- [x] Enable log levels per module (added in #78)
- [x] Log to the Unix syslog (added in #70)
- [x] [Log messages to a custom location](https://github.com/brson/rust-cookbook/issues/97)
- [x] [Include a timestamp on log messages](https://github.com/brson/rust-cookbook/issues/98)

Crate evaluation for `log`: See https://internals.rust-lang.org/t/crate-evaluation-for-2017-05-16-log/5185

Suggest ideas for other examples here if you have them!

**Comment by budziq** [comment]
I recall that sameone has posted interest in these examples on the libz-blitz thread but I would like to create PR later today for "Log to the Linux syslog" since I have a working example already

https://play.integer32.com/?gist=a21a9b6735f80d072ebea471840d2534&version=undefined

**Comment by rap2hpoutre** [comment]
Here is an example I just wrote for a simple use case (console log):

```rust
#[macro_use]
extern crate log;

use log::{LogRecord, LogLevel, LogMetadata, LogLevelFilter};

struct ConsoleLogger;

impl log::Log for ConsoleLogger {
    fn enabled(&self, metadata: &LogMetadata) -> bool {
        metadata.level() <= LogLevel::Info
    }

    fn log(&self, record: &LogRecord) {
        if self.enabled(record.metadata()) {
            println!("{} - {}", record.level(), record.args());
        }
    }
}

fn main() {
    log::set_logger(|max_log_level| {
                        max_log_level.set(LogLevelFilter::Info);
                        Box::new(ConsoleLogger)
                    })
            .unwrap();
    info!("hello log");
    warn!("warning");
    error!("oops");
}
```

Link to playground: http://play.integer32.com/?gist=80a6e5c21d710723a13a3817a6bb195c&version=undefined

Is this kind of example usefull? Did I missed something? Should I submit a PR?

**Comment by budziq** [comment]
@rap2hpoutre looks very nice indeed! I would just suggest following the convention about the snipet form described in https://brson.github.io/rust-cookbook/about.html#a-note-about-error-handling and explained in my own PR ;) (https://github.com/brson/rust-cookbook/pull/53#issuecomment-300244571)

Imho this would be a separate example. Something along the lines of  "Creating a custom logger".

**Comment by rap2hpoutre** [comment]
@budziq Thanks a lot! Here is a rewritten example:

```rust
#[macro_use]
extern crate log;

use log::{LogRecord, LogLevel, LogMetadata, LogLevelFilter, SetLoggerError};

struct ConsoleLogger;

impl log::Log for ConsoleLogger {
    fn enabled(&self, metadata: &LogMetadata) -> bool {
        metadata.level() <= LogLevel::Info
    }

    fn log(&self, record: &LogRecord) {
        if self.enabled(record.metadata()) {
            println!("{} - {}", record.level(), record.args());
        }
    }
}

fn init_logger() -> Result<(), SetLoggerError> {
    log::set_logger(|max_log_level| {
                        max_log_level.set(LogLevelFilter::Info);
                        Box::new(ConsoleLogger)
                    })?;
    Ok(())
}

fn main() {
    init_logger().unwrap();
    info!("hello log");
    warn!("warning");
    error!("oops");
}
```

Is this what you suggested? Did I understand well?

> Imho this would be a separate example. Something along the lines of "Creating a custom logger".

I think it's "**Log a message to the console**" (which covers). if it's almost OK, I can submit a PR then.

**Comment by budziq** [comment]
@rap2hpoutre As discussed on https://github.com/brson/rust-cookbook/pull/53 the typical form is 
```rust
// the real main with the whole setup and execution
fn run() -> Result<(), SetLoggerError> {
    log::set_logger(|max_log_level| {
                        max_log_level.set(LogLevelFilter::Info);
                        Box::new(ConsoleLogger)
                    })?;
    
    info!("hello log");
    warn!("warning");
    error!("oops");
    Ok(())
}

// boilerplate
fn main() {
    run().unwrap();
}
```
> I think it's "Log a message to the console" (which covers)

I would argue that this example is more involved (and rich with important usecase) than minimal (~5 lines) one that would use [`env_logger`](https://crates.io/crates/env_logger). But one of the maintainers would have to decide ;)

> if it's almost OK, I can submit a PR then.

I would submit PR anyway as code review is much easier and does not spam the tracking issue ;)

**Comment by dtolnay** [comment]
I checked off "Log to the Unix syslog" in #70 and "Log messages with a custom logger" in #74.

**Comment by brson** [comment]
Awesome. Thanks @budziq and @rap2hpoutre!

**Comment by bbigras** [comment]
An exemple with a timestamp could be nice. Maybe with the custom logger.

**Comment by dtolnay** [comment]
Thanks @bbigras! I added it to the checklist. Would you be interested in writing that example and submitting a PR?

**Comment by bbigras** [comment]
> Would you be interested in writing that example and submitting a PR

Yes

**Comment by meven** [comment]
I believe all the examples listed here have been implemented.
At the time of my writing those examples listed do not reflect they were merged :
    Log a debug message to the console
    Log an error message to the console
    Log messages to a custom location
    Include a timestamp on log messages

https://brson.github.io/rust-cookbook/app.html

**Comment by dtolnay** [comment]
You're right! Thanks for your help everybody.
